# This is a basic workflow to help you get started with Actions

name: Android CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
#       - name: Move directory 
#         run: cd presentation
      - name: Create env file
        run: touch presentation/gradle.properties
      - name: Setup base url paus
        env: 
          BASE_URL_PAUS: ${{ secrets.BASE_URL_PAUS }}
        run: echo -e "$BASE_URL_PAUS" >> presentation/gradle.properties
      - name: Setup base url siat
        env: 
          BASE_URL_SIAT: ${{ secrets.BASE_URL_SIAT }}
        run: echo -e "$BASE_URL_SIAT" >> presentation/gradle.properties
      - name: Setup client id
        env: 
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
        run: echo -e "$CLIENT_ID" >> presentation/gradle.properties
      - name: Setup client secret
        env: 
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        run: echo -e "$CLIENT_SECRET" >> presentation/gradle.properties
      - name: Setup grant type
        env: 
          PAUS_GRANT_TYPE: ${{ secrets.PAUS_GRANT_TYPE }}
        run: echo -e "$PAUS_GRANT_TYPE" >> presentation/gradle.properties
      - name: Setup paus scope
        env: 
          PAUS_SCOPE: ${{ secrets.PAUS_SCOPE }}
        run: echo -e "$PAUS_SCOPE" >> presentation/gradle.properties
      - name: Setup redirect uri
        env: 
          REDIRECT_URI: ${{ secrets.REDIRECT_URI }}
        run: echo -e "$REDIRECT_URI" >> presentation/gradle.properties
      - name: Cat
        run: cat presentation/gradle.properties
      - name: goback
        run: cd ..
      - name: Setup JDK
        uses: actions/setup-java@v2.0.0
        with: 
          java-version: 8
          distribution: 'adopt'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with gradle
        run: ./gradlew build
      - name: Upload APK
        uses: actions/upload-artifact@v2.2.3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk
